"""
AI Notes Summarizer
--------------------
Flask backend that:
  1. Serves the frontend (HTML/CSS/JS).
  2. Receives a transcript (produced client-side via the browser's
     Web Speech API, OR sent from an uploaded audio file transcribed
     via Groq Whisper) and returns a structured summary generated by
     an LLM (Groq's Llama 3.1 by default, free tier).

Environment variables required:
  GROQ_API_KEY  -> get a free key at https://console.groq.com/keys

Run locally:
  pip install -r requirements.txt
  cp .env.example .env   # then fill in your key
  python app.py
"""

import os
import json
import tempfile

from dotenv import load_dotenv
from flask import Flask, render_template, request, jsonify
from groq import Groq

load_dotenv()

app = Flask(__name__)

# 25 MB — Whisper API hard limit
app.config["MAX_CONTENT_LENGTH"] = 25 * 1024 * 1024

GROQ_API_KEY = os.environ.get("GROQ_API_KEY", "")
client = Groq(api_key=GROQ_API_KEY) if GROQ_API_KEY else None

SUMMARY_MODEL = "llama-3.3-70b-versatile"   # free on Groq
TRANSCRIBE_MODEL = "whisper-large-v3-turbo"  # free on Groq

SYSTEM_PROMPT = """You are a precise note-taking assistant. Given a raw speech
transcript, produce well-structured notes in JSON with this exact schema:

{
  "title": "short descriptive title (max 8 words)",
  "summary": "2-4 sentence plain-language summary of the whole recording",
  "key_points": ["bullet point 1", "bullet point 2", "..."],
  "action_items": ["any tasks/follow-ups mentioned, or empty list if none"]
}

Rules:
- Base everything ONLY on the transcript content, never invent facts.
- Keep key_points concise (one idea per bullet).
- If the transcript is very short or unclear, still do your best.
- Respond with ONLY the JSON object, no markdown fences, no extra text.
"""


@app.route("/")
def index():
    return render_template("index.html")


@app.route("/api/health")
def health():
    return jsonify({"status": "ok", "groq_configured": bool(GROQ_API_KEY)})


@app.errorhandler(413)
def too_large(_):
    return jsonify({"error": "File too large. Maximum size is 25 MB."}), 413


@app.route("/api/transcribe", methods=["POST"])
def transcribe():
    """Transcribe an uploaded audio file using Groq's hosted Whisper model."""
    if not client:
        return jsonify({"error": "Server is missing GROQ_API_KEY"}), 500

    if "audio" not in request.files:
        return jsonify({"error": "No audio file provided"}), 400

    audio_file = request.files["audio"]
    suffix = os.path.splitext(audio_file.filename or "audio.webm")[1] or ".webm"

    with tempfile.NamedTemporaryFile(suffix=suffix, delete=False) as tmp:
        audio_file.save(tmp.name)
        tmp_path = tmp.name

    try:
        with open(tmp_path, "rb") as f:
            result = client.audio.transcriptions.create(
                file=(os.path.basename(tmp_path), f.read()),
                model=TRANSCRIBE_MODEL,
                response_format="json",
            )
        return jsonify({"transcript": result.text})
    except Exception as e:
        return jsonify({"error": f"Transcription failed: {str(e)}"}), 500
    finally:
        try:
            os.remove(tmp_path)
        except OSError:
            pass


@app.route("/api/summarize", methods=["POST"])
def summarize():
    """Take a transcript (plain text) and return structured notes."""
    if not client:
        return jsonify({"error": "Server is missing GROQ_API_KEY"}), 500

    data = request.get_json(silent=True) or {}
    transcript = (data.get("transcript") or "").strip()

    if not transcript:
        return jsonify({"error": "transcript is empty"}), 400
    if len(transcript) < 5:
        return jsonify({"error": "transcript too short to summarize"}), 400

    try:
        completion = client.chat.completions.create(
            model=SUMMARY_MODEL,
            messages=[
                {"role": "system", "content": SYSTEM_PROMPT},
                {"role": "user", "content": f"Transcript:\n\n{transcript}"},
            ],
            temperature=0.3,
            max_tokens=800,
            response_format={"type": "json_object"},
        )
        raw = completion.choices[0].message.content
        notes = json.loads(raw)
        return jsonify({"notes": notes})
    except json.JSONDecodeError:
        return jsonify({"error": "Model returned invalid JSON", "raw": raw}), 502
    except Exception as e:
        return jsonify({"error": f"Summarization failed: {str(e)}"}), 500


if __name__ == "__main__":
    port = int(os.environ.get("PORT", 5000))
    app.run(host="0.0.0.0", port=port, debug=True)
